import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <div id="site-header-sticky-wrapper" className="wpex-sticky-header-holder not-sticky wpex-print-hidden wpex-can-sticky">
            <header className="wrapper bg-soft-primary">
              <nav className="navbar">
                <div className="container flex-lg-row flex-nowrap align-items-center">
                  <div className="navbar-brand w-100">
                    <a>
                      <Image className='brand' src="/img/shuaian.png" width={100} height={50} alt="Picture of the author"/>
                    </a>
                  </div>
                  <div id="offcanvas-nav" data-bs-scroll="true" className="navbar-collapse offcanvas offcanvas-nav offcanvas-start">
                    <div className="offcanvas-body ms-lg-auto d-flex flex-column h-100">
                      <ul className="navbar-nav">
                        <li className="nav-item dropdown dropdown-mega">
                          <a href="#" data-bs-toggle="dropdown" className="nav-link dropdown-toggle">Demos</a>
                        </li>
                        <li className="nav-item dropdown">
                          <a href="#" data-bs-toggle="dropdown" className="nav-link dropdown-toggle">Pages</a>
                        </li>
                        <li className="nav-item dropdown">
                          <a href="#" data-bs-toggle="dropdown" className="nav-link dropdown-toggle">Projects</a>
                        </li>
                        <li className="nav-item dropdown">
                          <a href="#" data-bs-toggle="dropdown" className="nav-link dropdown-toggle">Projects</a>
                        </li>
                        <li className="nav-item dropdown">
                          <a href="#" data-bs-toggle="dropdown" className="nav-link dropdown-toggle">Projects</a>
                        </li>
                        <li className="nav-item dropdown">
                          <a href="#" data-bs-toggle="dropdown" className="nav-link dropdown-toggle">Projects</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </nav>
            </header>
          </div>
        </div>
        {children}
        <footer>页尾</footer>
      </body>
    </html>
  )
}
